name: Tests

on:
    push:
        branches: ["main"]
    pull_request:

jobs:
    demo:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup | Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.21'

            - name: Build
              run: go build ./cmd/chaos

            - name: Run Demo
              run: |
                docker compose up -d
                curl --head -k -XGET --retry 50 --retry-all-errors --retry-delay 1 https://localhost:4052/_matrix/client/versions
                ./chaos -config config.demo.yaml -timeout_secs 25
            - name: Cleanup
              if: always()
              run: |
                ls -alh ./demo/data/hs2
                docker compose logs
                docker compose down -t 1 --remove-orphans

    tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup | Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.21'

            - name: Build
              run: go build ./cmd/chaos

            - name: Vet
              run: go vet ./...

            - name: Test
              run: go test ./...