name: Tests

on:
    push:
        branches: ["main"]
    pull_request:

permissions:
  packages: read
  # Note: from https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
  # > If you specify the access for any of these scopes, all of those that are not specified are set to none.

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup | Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.21'

            - name: Build
              run: go build ./cmd/chaos

            - name: Vet
              run: go vet ./...

            - name: Test
              run: go test ./...